### ISSUE TITLE
Subroutes

### ISSUE THREAD

**Issue by oriabukha-chwy** [micro-frontends-demo/container#18]
What if in Browser microsite I have a subroute '/browse/thank-you'. How to handle this situation, especially using <Link /> for moving to this route. 
I tried to do that, and it found 404: not found :(

Advice needed.

**Comment by camjackson** [comment]
That should be possible, it just depends on your router configuration. If you look at [this code](https://github.com/micro-frontends-demo/container/blob/master/src/App.js#L34-L37) you'll see that all of the routes are configured as `exact`, which means that e.g. `/about` will match the last one, but not `/about/faq`. If you want to deep-link to a nested route, without configuring that route in the container app, then probably just removing the `exact` flag would do it.

**Comment by oriabukha-chwy** [comment]
And what happens, when I develop my local microsite (sure related to this container) for example Browser. And that Browser has /browser/faq route? I can move there only from container, Is that possible I can move to there locally from localhost:3001 ?

**Comment by camjackson** [comment]
If you're developing a single micro frontend in isolation, and you want to see a page that is linked to from the outside, you can just type the URL directly in the address bar. That's what I do for the Restaurant micro frontend, which has routes like `/restaurant/:id`, which is linked to from the browse micro frontend.

Alternatively if you need something more sophisticated/dynamic, you could create a small wrapper for your micro frontend which is used when running it locally. That wrapper might render the micro frontend alongside a small navigation menu which has links to its various pages. For the Restaurant example above, you could edit its index.html, and right before [this line](https://github.com/micro-frontends-demo/restaurant-order/blob/master/public/index.html#L16) add a few `<a>` tags that link to various different restaurants.
