### ISSUE TITLE
ReferenceError: React is not defined when start project

### ISSUE THREAD

**Issue by thanhpd-teko** [micro-frontends-demo/container#2]
- Step:
+ yarn install
+ yarn start
On browser, show error ReferenceError: React is not defined
![image](https://user-images.githubusercontent.com/47600586/62194343-e08eb200-b3a3-11e9-84c7-4d392b40410e.png)

**Comment by deggers** [comment]
Hey, i recommend to start the scripts in the following order:
1. content
2. container
3. browse
4. restaurant-order

**Comment by thanhpd-teko** [comment]
Yep, thank you. It's working now. Btw, it's truly revolution of frontend.

**Comment by pbalenzuela** [comment]
@deggers don't you think that requiring other micro front ends breaks the isolation goal we're trying to solve here? I understand that not bundling all the dependencies in each micro front end makes all the scripts smaller but still, it is a little odd to me. What do you think?

**Comment by deggers** [comment]
I might misunderstan you, but it is not required to use different frameworks in each micro front end. It's rather the possibility to mix and match if needed. When you created a huge monolithic frontend a framework shift becomes quite hard. And software architecture is about keeping your system in a state which can adapt to change. What you say? Did i misinterpreted your question?  @pbalenzuela

**Comment by camjackson** [comment]
@pbalenzuela You're right - sharing dependencies between MFEs creates coupling, which can be a problem. It's all about finding the right balance / tradeoff between total isolation and optimised performance.

Sharing React for these very small MFEs is pretty unnecessary, but it's just an example of what is possible.

Read more:
- https://martinfowler.com/articles/micro-frontends.html#CommonContent
- https://martinfowler.com/articles/micro-frontends.html#PayloadSize
