### ISSUE TITLE
Can we integrate Angular or Vue services to the container?

### ISSUE THREAD

**Issue by pushpendra2011** [micro-frontends-demo/container#25]
This is not a bug related to the existing project, I tried integrating container with an angular app and have come across a few blockers. In `Microfrontend` component, we are fetching `asset-manifest.json` from host and setting `src` as `script.src = ${host}${manifest[main.js]}`. Application that I was using as an Angular service is a boilerplate project that has `manifest.webmanifest` already created like below (unlike React where `asset-manifest` gets created internally I assume)-

```
{
  "name": "ngX-Rocket",
  "short_name": "ngX-Rocket",
  "theme_color": "#488aff",
  "background_color": "#488aff",
  "display": "standalone",
  "scope": "./",
  "start_url": "./",
  "icons": [
    {
      "src": "assets/ngx-rocket-logo.png",
      "sizes": "512x512",
      "type": "image/png",
      "purpose": "maskable any"
    },
    {
      "src": "assets/ngx-rocket-logo@192.png",
      "sizes": "192x192",
      "type": "image/png",
      "purpose": "maskable any"
    }
  ]
}
```
Can you shed some light on how can we make the communication possible between container and services that are using platforms like Angular or Vue?

**Comment by camjackson** [comment]
Hi @Pushpendra92 - this repo is just some example code to show how a simple react-react MFE integration can work. Mixing other frameworks in is beyond the scope of this project.
