### ISSUE TITLE
Use different syntax defining ports for Mac and Windows

### ISSUE THREAD

**Issue by vzeleniuk** [micro-frontends-demo/container#26]
The original implementation will not work on Windows. It is for Mac OS and Linux: 
`"start": "PORT=3001 react-scripts start",`

There could be commands for Windows and Mac:
`"start-mac": "PORT=3001 react-scripts start",`
`"start-windows": "set PORT=3001 && react-scripts start",` or `start-win`

**Comment by camjackson** [comment]
Thanks @vzeleniuk, I don't disagree but seeing as this is just example code, I would rather keep it as simple and concise as possible, rather than have it be feature complete.
